const mongoose = require('mongoose');
var uuid = require('node-uuid');


const productSchema = new mongoose.Schema({
  // _id is generated by default if not provided
  // uuid v4: https://www.uuidgenerator.net/version4
  // id in products.json obtained from site
  _id: {
    required: true,
    type: mongoose.Schema.Types.ObjectId,
    unique: true,
    auto: true,
  },
  title: {
    type: String,
    required: [true, 'Please add a Product title']
  },
  description: {
    type: String,
    required: [true, 'Please add a description']
  },
  price: {
    type: String,
    required: [true, 'Please add price']
  },
  imageUrl: {
    type: String,
    required: [true, 'Please add image url']
  }
});

module.exports = mongoose.model('products', productSchema);
